name: Lockpick
main: com.voxela.lockpick.Main
version: 1.3
author: Ladinn
websote: http://www.voxela.com
depend: [WorldEdit, WorldGuard]
softdepend: [TitleAPI]
commands:
    lockpick:
        description: Main command.
        usage: /<command>
permissions:
   voxela.lockpick.*:
     description: Gives access to all permissions.
     children:
       voxela.lockpick.door: true
       voxela.lockpick.chest: true
       voxela.lockpick.admin: true
   voxela.lockpick.admin:
     description: Administrator command permissions.
   voxela.lockpick.door:
     description: Allows the player to lockpick a door.
     default: false
   voxela.lockpick.chest:
     description: Allows the player to lockpick a chest.
     default: false